# Generated by Django 5.0 on 2023-12-16 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0002_administrator_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='courses',
        ),
        migrations.AddField(
            model_name='student',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='college.course'),
        ),
        migrations.AddField(
            model_name='student',
            name='lectures',
            field=models.ManyToManyField(related_name='students', to='college.lecture'),
        ),
    ]
