# Generated by Django 5.0 on 2023-12-16 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('college', '0003_remove_student_courses_student_course_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrator',
            name='password',
        ),
        migrations.RemoveField(
            model_name='administrator',
            name='username',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='password',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
